#!/bin/bash
set PHANTOMJS_BIN = phantomjs
BASE_DIR=`dirname $0`
PORT='9100'
if [ -x "testacular" ]; then
  testacular start $BASE_DIR/../config/testacular-e2e.conf.js run --runner-port $PORT
else
  node $BASE_DIR/../node_modules/testacular/bin/testacular run --runner-port $PORT
fi
